---
- name: Deploy Scientific Calculator Application
  hosts: local
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: latest

    - name: Log in to Docker Hub
      docker_login:
        username: radhika20
        password: "{{ lookup('env', 'DOCKERHUB_PASSWORD') }}"

    - name: Pull the Scientific Calculator Docker image
      docker_image:
        name: radhika20/scientific-calculator
        source: pull

    - name: Run the Scientific Calculator container
      docker_container:
        name: scientific-calculator
        image: radhika20/scientific-calculator
        state: started
        ports:
          - "80:80"
